BeginHeader
Caret-Version 5.615
Date 2015-03-04T11:00:23
category Individual
encoding ASCII
space OTHER
species Human
structure left
subject Conte69
EndHeader

CLOSEDtopo_file Conte69.L.32k_fs_LR.topo.gii 
FIDUCIALcoord_file Conte69.L.pial.32k_fs_LR.coord.gii 
FIDUCIALcoord_file Conte69.L.white.32k_fs_LR.coord.gii 
FIDUCIALcoord_file Conte69.L.midthickness.32k_fs_LR.coord.gii 
INFLATEDcoord_file Conte69.L.inflated.32k_fs_LR.coord.gii 
VERY_INFLATEDcoord_file Conte69.L.very_inflated.32k_fs_LR.coord.gii 
SPHERICALcoord_file Conte69.L.sphere.32k_fs_LR.coord.gii 
INFLATEDsurface_file ../../../32k_ConteAtlas_v2/Conte69.R.midthickness.32k_fs_LR.surf.gii 
INFLATEDsurface_file ../../../32k_ConteAtlas_v2/Conte69.L.inflated.32k_fs_LR.surf.gii 
INFLATEDsurface_file ../../../32k_ConteAtlas_v2/Conte69.R.inflated.32k_fs_LR.surf.gii 
INFLATEDsurface_file Conte69.R.inflated.32k_fs_LR.surf.gii 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges1.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges2.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges3.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges4.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges5.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges6.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges7.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges8.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges9.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges10.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges11.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges12.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges13.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges14.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges15.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges16.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges17.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges18.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges19.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges20.png 
image_file ../../../../../Users/laumannt/Desktop/RSN_Power_v_AllC_edges/RSN_Power_v_AllC_edges21.png 
paint_file ../../../FinalLabels/Yeo2011_17Networks.L.32k_fs_LR.label.gii.paint 
paint_file ../../../FinalLabels/Yeo2011_7Networks.L.32k_fs_LR.label.gii.paint 
paint_file ../../../FinalLabels/Yeo2011_17Networks.L.32k_fs_LR.paint 
paint_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.paint 
paint_file ../../../32k_ConteAtlas_v2/medial_wall.L.32k_fs_LR.label.gii.paint 
paint_file ../../../FinalLabels/Yeo2011_7Networks.L.32k_fs_LR.label.gii 
paint_file ../../../FinalLabels/Yeo2011_17Networks.L.32k_fs_LR.label.gii 
paint_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.label.gii 
paint_file ../../../32k_ConteAtlas_v2/RSN_Networks_Power2.paint 
paint_file ../../../32k_ConteAtlas_v2/RSN_Networks_Power.paint 
paint_file ../../../../../Users/laumannt/Downloads/Conte69_atlas-v2.LR.32k_fs_LR.wb/32k_ConteAtlas_v2/test.paint 
paint_file ../../../../../Users/laumannt/Downloads/Conte69_atlas-v2.LR.32k_fs_LR.wb/32k_ConteAtlas_v2/RSN-networks.L.32k_fs_LR.label.gii 
paint_file ../../../32k_ConteAtlas_v2/parcellations_VGD11b.R.32k_fs_LR.label.gii 
paint_file Parcels_L.label.gii 
INFLATEDborder_file ../../../test.border 
border_color_file ../../../FinalLabels/Yeo2011_17Networks.L.32k_fs_LR.bordercolor 
border_color_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.bordercolor 
border_color_file ../RestingState/Consensus/ConsensusMapv1_L.bordercolor 
border_color_file test.bordercolor 
borderproj_file ../../../test.borderproj 
borderproj_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.borderproj 
borderproj_file ../RestingState/Consensus/ConsensusMapv1_L.borderproj 
metric_file ../../../all_meanimage_32k_fs_LR.func.gii 
metric_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.gradbin.func.gii 
metric_file ../../../FinalLabels/Power_Neuron11_dil.L.32_fs_LR.neighbordermatlab.func.gii 
metric_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.grad.func.gii 
metric_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.func.gii 
metric_file ../../../FinalLabels/Power_Neuron11_dil.L.32k_fs_LR.metric 
metric_file ../../../fcMapping_redux/surfsmooth_bandpass_surfreg_32k_gradients/smooth255preedge_surfsmooth_ztrans_bandpass_surfreg_32K_AllC_avg_edge_avg_smooth_L_noalone.func.gii 
metric_file ../../../32k_ConteAtlas_v2/all_meanimage.func.gii 
metric_file ../../../fcMapping_redux/bandpass_surfreg_32k_gradients/bandpass_surfreg_32K_AllC_avg_edge_avg_smooth_L_noalone.func.gii 
metric_file ../../../fcMapping_redux/surfreg_32k_gradients/surfreg_32K_AllC_avg_edge_avg_smooth_L_noalone_invert.func.gii 
metric_file ../../../fcMapping_redux/surfsmooth_bandpass_surfreg_32k_gradients/smooth255preedge_surfsmooth_ztrans_bandpass_surfreg_32K_AllC_avg_edge_avg_smooth_R_noalone.func.gii 
metric_file Parcels_L.func.gii 
metric_file Conte69.L.thickness.32k_fs_LR.shape.gii 
metric_file Conte69.L.corrThickness.32k_fs_LR.shape.gii 
metric_file Conte69.L.MyelinMap.32k_fs_LR.func.gii 
metric_file Conte69.L.SmoothedMyelinMap.32k_fs_LR.func.gii 
surface_shape_file Conte69.L.sulc.32k_fs_LR.shape.gii 
surface_shape_file Conte69.L.curvature.32k_fs_LR.shape.gii 
foci_file ../../../JP_jet.foci 
foci_file ../../../LCP_jet.foci 
foci_color_file ../../../JP_jet_col1.focicolor 
foci_color_file ../../../LCP_jet_col1.focicolor 

