<?xml version="1.0" encoding="UTF-8"?>
<Spec_File>
   <FileHeader>
      <Element>
         <Name><![CDATA[Caret-Version]]></Name>
         <Value><![CDATA[5.615]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[Date]]></Name>
         <Value><![CDATA[2013-07-09T17:48:04]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[category]]></Name>
         <Value><![CDATA[Individual]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[encoding]]></Name>
         <Value><![CDATA[XML]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[space]]></Name>
         <Value><![CDATA[MRITOTAL]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[species]]></Name>
         <Value><![CDATA[Human]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[structure]]></Name>
         <Value><![CDATA[left]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[subject]]></Name>
         <Value><![CDATA[cerebral]]></Value>
      </Element>
   </FileHeader>
   <volume_functional_file>
      <file1><![CDATA[allregions_cluster.4dfp.ifh]]></file1>
      <file2><![CDATA[allregions_cluster.4dfp.img]]></file2>
   </volume_functional_file>
   <CLOSEDtopo_file>
      <file1><![CDATA[Conte69.L.164k_fs_LR.topo.gii]]></file1>
   </CLOSEDtopo_file>
   <CUTtopo_file>
      <file1><![CDATA[colin.cerebral.L.flat.164k_fs_LR.topo.gii]]></file1>
   </CUTtopo_file>
   <FIDUCIALcoord_file>
      <file1><![CDATA[Conte69.L.midthickness.164k_fs_LR.coord.gii]]></file1>
   </FIDUCIALcoord_file>
   <INFLATEDcoord_file>
      <file1><![CDATA[Conte69.L.inflated.164k_fs_LR.coord.gii]]></file1>
   </INFLATEDcoord_file>
   <VERY_INFLATEDcoord_file>
      <file1><![CDATA[Conte69.L.very_inflated.164k_fs_LR.coord.gii]]></file1>
   </VERY_INFLATEDcoord_file>
   <FLATcoord_file>
      <file1><![CDATA[colin.cerebral.L.flat.164k_fs_LR.coord.gii]]></file1>
   </FLATcoord_file>
   <scene_file>
      <file1><![CDATA[atlas.L.standard-scenes-v2.164k_fs_LR.scene]]></file1>
   </scene_file>
   <paint_file>
      <file1><![CDATA[RSN-networks.L.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[parcellations_VGD11b.L.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[separate_10FP_20COplusregs_LEFT.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[Show10FPand20COplusregs.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[map_data_0_Conte69_LEFT_midthickness_164k_fs_LR_19_Feb_2013_16_39_37.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[Power_Neuron11_dil.L.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_ANOVA_zstats_z>2.5_Conte69_LEFT_midthickness_164k_fs_LR_24_Mar_2013_13_38_06.atlas.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_FPW2_LPW2_RW2_lex_time_z>2.5_Conte69_LEFT_midthickness_164k_fs_LR_25_Mar_2013_16_41_57.atlas.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_ANOVA_ROI_z>2.5_2_Conte69_LEFT_midthickness_164k_fs_LR_26_Mar_2013_15_02_24.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_matched_LoHi_DPR_z2.5_Conte69_LEFT_midthickness_164k_fs_LR_12_Apr_2013_15_59_59.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[Anal1_regANOVA_p05_ROI_Conte69_LEFT_midthickness_164k_fs_LR_26_Apr_2013_11_57_31.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_FPW_LPW_regANOVA_1X2_2X2_ROI_tk2_Conte69_LEFT_midthickness_164k_fs_LR_29_Apr_2013_13_49_44.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[ANAL1_FPW_LPW_vox+regwiseANOVA_p05ROI_Conte69_LEFT_midthickness_164k_fs_LR_30_Apr_2013_12_12_01.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[1X2_LPW2_RW2_voxwise_ROI_Conte69_LEFT_midthickness_164k_fs_LR_22_May_2013_11_39_25.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[postRTNA_ROI_Conte69_LEFT_midthickness_164k_fs_LR_1_Jun_2013_21_41_54.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[tk2_postRTNA_LPW2_RW2_ROI_Conte69_LEFT_midthickness_164k_fs_LR_2_Jun_2013_21_05_14.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[tk3_RTNA_LPW2_RW2_ROI_LEFT_midthickness_164k_fs_LR_5_Jun_2013_18_03_45.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[temptemp64k_fs_LR_6_Jun_2013_14_02_20.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[consol_ROI_4_br_behav_anal_Conte69_LEFT_midthickness_164k_fs_LR_25_Jun_2013_19_04_17.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[anim_artif_ROI_Conte69_LEFT_midthickness_164k_fs_LR_26_Jun_2013_12_03_54.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[anim_artif_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_26_Jun_2013_12_04_07.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[anim_artif_take2_Conte69_LEFT_midthickness_164k_fs_LR_26_Jun_2013_13_46_01.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[clustering_2X3ANOVA_146ROI_Conte69_LEFT_midthickness_164k_fs_LR_27_Jun_2013_01_52_32.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[All_clusters_Conte69_LEFT_midthickness_164k_fs_LR_29_Jun_2013_14_10_00.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[LP1_LP2_FPRWmasked_Conte69_LEFT_midthickness_164k_fs_LR_5_Jul_2013_16_46_53.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[FP_LP_RW_D1vD2_day_time_z3.5_time_z7_ROI_Conte69_LEFT_midthickness_164k_fs_LR_9_Jul_2013_15_22_09.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[../RestingState/Consensus/ConsensusMapvFinal_164k_L.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[../../laumannt/ConsensusMapvFinal_L.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <area_color_file>
      <file1><![CDATA[FP_LP_RW_D1vD2_ROI_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[anim_artif_Human.cerebral.R.area_color_file_121.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[clustering_2X3_146ROI_9clust_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[anim_artif_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[RTNA_Anal1_reg_voxwise_ANOVA_p05ROI_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Anal1_reg_voxwise_ANOVA_p05ROI_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Anal1_regANOVA_p05ROI_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[n28_ROIcolors_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[n28_ANOVA_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[LeftorRIght_colorcodeCOneighbors.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[IndividualLFPregions_022013.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Left_separateCOcluster.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[LeftorRIght2_colorcodeCOneighbors.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Left_colorcodeCOneighbors.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[artif_anim_z_Human.cerebral.L.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <border_color_file>
      <file1><![CDATA[ConsensusMapvFinal_L.bordercolor]]></file1>
   </border_color_file>
   <border_color_file>
      <file1><![CDATA[Power_Neuron11_dil.L.164k_fs_LR.bordercolor]]></file1>
   </border_color_file>
   <border_color_file>
      <file1><![CDATA[parcellations_VGD11b.bordercolor]]></file1>
   </border_color_file>
   <border_color_file>
      <file1><![CDATA[../RestingState/Consensus/ConsensusMapvFinal_L.bordercolor]]></file1>
   </border_color_file>
   <borderproj_file>
      <file1><![CDATA[ConsensusMapvFinal_L.borderproj]]></file1>
   </borderproj_file>
   <borderproj_file>
      <file1><![CDATA[Power_Neuron11_dil.L.164k_fs_LR.borderproj]]></file1>
   </borderproj_file>
   <borderproj_file>
      <file1><![CDATA[../RestingState/Consensus/ConsensusMapvFinal_164k_L.borderproj]]></file1>
   </borderproj_file>
   <metric_file>
      <file1><![CDATA[Human.cerebral.L.metricfile_18.163842.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_ANOVA_zstats_Conte69_LEFT_midthickness_164k_fs_LR_21_Mar_2013_15_55_55.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_ANOVA_zstats_2_Conte69_LEFT_midthickness_164k_fs_LR_22_Mar_2013_13_42_52.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_FPW2_LPW2_RW2_lexicality_time_zstat_Conte69_LEFT_midthickness_164k_fs_LR_25_Mar_2013_16_22_45.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_ANOVA_zstats_3_LEFT_midthickness_164k_fs_LR_26_Mar_2013_14_58_34.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_DPR_ANOVA_matched_Conte69_LEFT_midthickness_164k_fs_LR_9_Apr_2013_12_39_52.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[tk2_FPW2_LPW2_lexicality_time_DPRIME_Conte69_LEFT_midthickness_164k_fs_LR_10_Apr_2013_17_06_30.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[matched_LoHi_DPR_zstats_Conte69_LEFT_midthickness_164k_fs_LR_12_Apr_2013_11_33_20.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_LPW2RW2_v_FPW2_time_zstat_LEFT_midthickness_164k_fs_LR_16_Apr_2013_15_18_14.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[sem_facil_item_anal_time_zstat_Conte69_LEFT_midthickness_164k_fs_LR_23_May_2013_12_20_11.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[FPW2_LPW2_lex_time_RT_NA_zstat_Conte69_LEFT_midthickness_164k_fs_LR_31_May_2013_11_36_15.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[FPW2_LPW2_X_time_RTNA_v_old_zstat_Conte69_LEFT_midthickness_164k_fs_LR_31_May_2013_12_55_10.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[postRTNA_anova_zstats_Conte69_LEFT_midthickness_164k_fs_LR_1_Jun_2013_20_42_11.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[RTNA_sem_facil_mainEff_item_Conte69_LEFT_midthickness_164k_fs_LR_3_Jun_2013_12_29_30.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[sem_cat_anal_zstats_Conte69_LEFT_midthickness_164k_fs_LR_4_Jun_2013_09_51_03.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[tk2_RTNA_LP2_RW2_lex_time_zstat_LEFT_Conte69_midthickness_164k_fs_LR_5_Jun_2013_18_15_42.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[clus_anal_zstats_Conte69_LEFT_midthickness_164k_fs_LR_1_Jul_2013_09_28_01.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[lex_semCat_anal_n28_Conte69_LEFT_midthickness_164k_fs_LR_5_Jul_2013_11_04_05.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[rep_suppr_anal_Conte69_LEFT_midthickness_164k_fs_LR_5_Jul_2013_15_41_16.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[rep_suppr_anal_n28_Conte69_LEFT_midthickness_164k_fs_LR_5_Jul_2013_15_52_11.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[Conte69.L.MyelinMap.164k_fs_LR.func.gii]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[Conte69.L.SmoothedMyelinMap.164k_fs_LR.func.gii]]></file1>
   </metric_file>
   <surface_shape_file>
      <file1><![CDATA[Conte69.L.164k_fs_LR.shape.gii]]></file1>
   </surface_shape_file>
   <foci_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_fpw2_TP3_4_ave_matched_class_16-Apr-2013_140_acc90_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_lpw2_TP3_4_ave_matched_class_16-Apr-2013_145_acc92_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_rw2_TP3_4_ave_matched_class_16-Apr-2013_150_acc85_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[../event_rel_age/lexicalization/lex_fMRI/clean_glms/n28/n28_DPR_match_SVM/n28_METRz3.5_BB264_HiLoDPR_fpw2_TP3_4_ave_matched_class_16-Apr-2013_140_acc90_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[RSN-nodes_PCN11.L.c5.foci]]></file1>
   </foci_file>
   <foci_color_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_rw2_TP3_4_ave_matched_class_16-Apr-2013_150_acc85_feat.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_fpw2_TP3_4_ave_matched_class_16-Apr-2013_140_acc90_feat.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_lpw2_TP3_4_ave_matched_class_16-Apr-2013_145_acc92_feat.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[RSN-nodes_PCN11.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[Parcels_class.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[ActivationFoci_ParietoFrontal.focicolor]]></file1>
   </foci_color_file>
   <fociproj_file>
      <file1><![CDATA[RSN-nodes_PCN11.L.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[Parcels_GV11.L.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[ActivationFoci_ParietoFrontal.L.164k_fs_LR.c5.fociproj]]></file1>
   </fociproj_file>
   <study_metadata_file>
      <file1><![CDATA[VanEssen_CC12.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Yeo_JNP11.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Power_Neuron11.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Glasser_JN11.study]]></file1>
   </study_metadata_file>
</Spec_File>
