<?xml version="1.0" encoding="UTF-8"?>
<Spec_File>
   <FileHeader>
      <Element>
         <Name><![CDATA[Caret-Version]]></Name>
         <Value><![CDATA[5.65]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[Date]]></Name>
         <Value><![CDATA[2013-07-09T15:55:43]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[category]]></Name>
         <Value><![CDATA[Individual]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[encoding]]></Name>
         <Value><![CDATA[XML]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[space]]></Name>
         <Value><![CDATA[FNIRT]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[species]]></Name>
         <Value><![CDATA[Human]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[structure]]></Name>
         <Value><![CDATA[right]]></Value>
      </Element>
      <Element>
         <Name><![CDATA[subject]]></Name>
         <Value><![CDATA[cerebral]]></Value>
      </Element>
   </FileHeader>
   <CLOSEDtopo_file>
      <file1><![CDATA[Conte69.R.164k_fs_LR.topo.gii]]></file1>
   </CLOSEDtopo_file>
   <CUTtopo_file>
      <file1><![CDATA[colin.cerebral.R.flat.164k_fs_LR.topo.gii]]></file1>
   </CUTtopo_file>
   <FIDUCIALcoord_file>
      <file1><![CDATA[Conte69.R.midthickness.164k_fs_LR.coord.gii]]></file1>
   </FIDUCIALcoord_file>
   <INFLATEDcoord_file>
      <file1><![CDATA[Conte69.R.inflated.164k_fs_LR.coord.gii]]></file1>
   </INFLATEDcoord_file>
   <VERY_INFLATEDcoord_file>
      <file1><![CDATA[Conte69.R.very_inflated.164k_fs_LR.coord.gii]]></file1>
   </VERY_INFLATEDcoord_file>
   <FLATcoord_file>
      <file1><![CDATA[colin.cerebral.R.flat.164k_fs_LR.coord.gii]]></file1>
   </FLATcoord_file>
   <scene_file>
      <file1><![CDATA[atlas.R.standard-scenes-v2.164k_fs_LR.scene]]></file1>
   </scene_file>
   <paint_file>
      <file1><![CDATA[FP_LP_RW_D1vD2_day_time_z3.5_time_z7_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_9_Jul_2013_15_22_20.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[LP1_LP2_FPRWmasked_Conte69_RIGHT_midthickness_164k_fs_LR_5_Jul_2013_16_47_00.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[All_clusters_Conte69_RIGHT_midthickness_164k_fs_LR_29_Jun_2013_14_10_08.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[clustering_2X3ANOVA_146ROI_Conte69_RIGHT_midthickness_164k_fs_LR_27_Jun_2013_01_52_40.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[anim_artif_take2_Conte69_RIGHT_midthickness_164k_fs_LR_26_Jun_2013_13_46_11.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[anim_artif_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_26_Jun_2013_12_04_07.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[consol_ROI_4_br_behav_anal_Conte69_RIGHT_midthickness_164k_fs_LR_25_Jun_2013_19_04_25.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[tk3_RTNA_LPW2_RW2_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_5_Jun_2013_18_03_52.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[tk2_postRTNA_LPW2_RW2_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_2_Jun_2013_21_05_24.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[postRTNA_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_1_Jun_2013_21_42_41.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[1X2_LPW2_RW2_voxwise_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_22_May_2013_11_39_37.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[ANAL1_FPW_LPW_vox+regwiseANOVA_p05ROI_Conte69_RIGHT_midthickness_164k_fs_LR_30_Apr_2013_12_12_13.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_FPW_LPW_regANOVA_1X2_2X2_ROI_tk2_Conte69_RIGHT_midthickness_164k_fs_LR_29_Apr_2013_13_49_53.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[Anal1_regANOVA_p05_ROI_Conte69_RIGHT_midthickness_164k_fs_LR_26_Apr_2013_11_57_42.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_matched_LoHi_DPR_z2.5_Conte69_RIGHT_midthickness_164k_fs_LR_12_Apr_2013_16_00_16.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_ANOVA_ROI_z>2.5_2_Conte69_RIGHT_midthickness_164k_fs_LR_26_Mar_2013_15_02_41.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_FPW2_LPW2_RW2_lex_time_z>2.5_Conte69_RIGHT_midthickness_164k_fs_LR_25_Mar_2013_16_42_09.atlas.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[n28_ANOVA_zstats_z>2.5_Conte69_RIGHT_midthickness_164k_fs_LR_24_Mar_2013_13_38_19.atlas.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[Power_Neuron11_dil.R.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[map_data_1_Conte69_RIGHT_midthickness_164k_fs_LR_19_Feb_2013_16_39_48.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[separate_20COplus_10FPregsRIGHT.paint]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[RSN-networks.R.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <paint_file>
      <file1><![CDATA[parcellations_VGD11b.R.164k_fs_LR.label.gii]]></file1>
   </paint_file>
   <area_color_file>
      <file1><![CDATA[FP_LP_RW_D1vD2_ROI_Human.cerebral.L.area_color_file_117.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[clustering_2X3_146ROI_9clust_Human.cerebral.R.area_color_file_1.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[artif_animHuman.cerebral.R.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[anim_artif_Human.cerebral.L.area_color_file_118.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[RTNA_Anal1_reg_voxwise_ANOVA_p05ROI_Human.cerebral.R.area_color_file_1.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Anal1_reg_voxwise_ANOVA_p05ROI_Human.cerebral.R.area_color_file_1.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Anal1_regANOVA_p05ROI_Human.cerebral.R.area_color_file_1.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[Anal1_regANOVA_p05ROI_Human.cerebral.L.area_color_file_139.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[n28_ROIcolors_Human.cerebral.R.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[n28_ANOVA_Human.cerebral.R.area_color_file_2.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[RIGHT_separateCOcluster.areacolor]]></file1>
   </area_color_file>
   <area_color_file>
      <file1><![CDATA[artif_anim_z_Human.cerebral.L.area_color_file_118.areacolor]]></file1>
   </area_color_file>
   <border_color_file>
      <file1><![CDATA[ConsensusMapvFinal_R.bordercolor]]></file1>
   </border_color_file>
   <border_color_file>
      <file1><![CDATA[Power_Neuron11_dil.R.164k_fs_LR.bordercolor]]></file1>
   </border_color_file>
   <border_color_file>
      <file1><![CDATA[parcellations_VGD11b.bordercolor]]></file1>
   </border_color_file>
   <borderproj_file>
      <file1><![CDATA[ConsensusMapvFinal_R.borderproj]]></file1>
   </borderproj_file>
   <borderproj_file>
      <file1><![CDATA[Power_Neuron11_dil.R.164k_fs_LR.borderproj]]></file1>
   </borderproj_file>
   <borderproj_file>
      <file1><![CDATA[parcellations_VGD11b.R.164k_fs_LR.borderproj]]></file1>
   </borderproj_file>
   <atlas_file>
      <file1><![CDATA[n28_ANOVA_zstats_z>2.5_Conte69_RIGHT_midthickness_164k_fs_LR_24_Mar_2013_13_38_19.atlas.paint]]></file1>
   </atlas_file>
   <metric_file>
      <file1><![CDATA[rep_suppr_anal_n28_Conte69_RIGHT_midthickness_164k_fs_LR_5_Jul_2013_15_52_35.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[map_data_16_Conte69_RIGHT_midthickness_164k_fs_LR_5_Jul_2013_15_41_34.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[lex_semCat_anal_n28_Conte69_RIGHT_midthickness_164k_fs_LR_5_Jul_2013_11_04_14.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[clus_anal_zstats_Conte69_RIGHT_midthickness_164k_fs_LR_1_Jul_2013_09_28_10.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[tk2_RTNA_LP2_RW2_lex_time_zstat_Conte69_RIGHT_midthickness_164k_fs_LR_5_Jun_2013_18_15_49.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[sem_cat_anal_zstats_Conte69_RIGHT_midthickness_164k_fs_LR_4_Jun_2013_09_51_15.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[RTNA_sem_facil_mainEff_item_Conte69_RIGHT_midthickness_164k_fs_LR_3_Jun_2013_12_29_38.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[postRTNA_anova_zstats_Conte69_RIGHT_midthickness_164k_fs_LR_1_Jun_2013_20_42_21.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[FPW2_LPW2_X_time_RTNA_v_old_zstat_Conte69_RIGHT_midthickness_164k_fs_LR_31_May_2013_12_55_18.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[FPW2_LPW2_lex_time_RT_NA_zstat_Conte69_RIGHT_midthickness_164k_fs_LR_31_May_2013_11_36_23.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[sem_facil_item_anal_time_zstat_Conte69_RIGHT_midthickness_164k_fs_LR_23_May_2013_12_20_21.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_LPW2RW2_v_FPW2_time_zstat_Conte69_RIGHT_midthickness_164k_fs_LR_16_Apr_2013_15_18_25.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[matched_LoHi_DPR_zstats_Conte69_RIGHT_midthickness_164k_fs_LR_12_Apr_2013_11_33_32.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_ANOVA_zstats_3_Conte69_RIGHT_midthickness_164k_fs_LR_26_Mar_2013_14_58_50.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_FPW2_LPW2_RW2_lexicality_time_zstat_Conte69_RIGHT_midthickness_164k_fs_LR_25_Mar_2013_16_22_56.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_ANOVA_zstats_2_Conte69_RIGHT_midthickness_164k_fs_LR_22_Mar_2013_13_43_08.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[n28_ANOVA_zstats_Conte69_RIGHT_midthickness_164k_fs_LR_21_Mar_2013_15_56_09.metric]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[Conte69.R.MyelinMap.164k_fs_LR.func.gii]]></file1>
   </metric_file>
   <metric_file>
      <file1><![CDATA[Conte69.R.SmoothedMyelinMap.164k_fs_LR.func.gii]]></file1>
   </metric_file>
   <surface_shape_file>
      <file1><![CDATA[Conte69.R.164k_fs_LR.shape.gii]]></file1>
   </surface_shape_file>
   <foci_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_fpw2_TP3_4_ave_matched_class_16-Apr-2013_140_acc90_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_lpw2_TP3_4_ave_matched_class_16-Apr-2013_145_acc92_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_rw2_TP3_4_ave_matched_class_16-Apr-2013_150_acc85_feat.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[n12_1X2X3METRz2_BB264_lpw2rw2_n50_150_TP3_4_ave_class__07-Jan-2013_110_feat_100perc.csv.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[RSN-nodes_PCN11.R.c5.foci]]></file1>
   </foci_file>
   <foci_file>
      <file1><![CDATA[RSN-nodes_PCN11.L.c5.foci]]></file1>
   </foci_file>
   <foci_color_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_rw2_TP3_4_ave_matched_class_16-Apr-2013_150_acc85_feat.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_fpw2_TP3_4_ave_matched_class_16-Apr-2013_140_acc90_feat.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[n28_METRz3.5_BB264_HiLoDPR_lpw2_TP3_4_ave_matched_class_16-Apr-2013_145_acc92_feat.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[n12_1X2X3METRz2_BB264_lpw2rw2_n50_150_TP3_4_ave_class__07-Jan-2013_110_feat_100perc.csv.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[RSN-nodes_PCN11.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[Parcels_class.focicolor]]></file1>
   </foci_color_file>
   <foci_color_file>
      <file1><![CDATA[ActivationFoci_ParietoFrontal.focicolor]]></file1>
   </foci_color_file>
   <fociproj_file>
      <file1><![CDATA[RSN-nodes_PCN11.R.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[RSN-nodes_PCN11.L.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[Parcels_GV11.R.164k_fs_LR.fociproj]]></file1>
   </fociproj_file>
   <fociproj_file>
      <file1><![CDATA[ActivationFoci_ParietoFrontal.R.164k_fs_LR.c5.fociproj]]></file1>
   </fociproj_file>
   <study_metadata_file>
      <file1><![CDATA[VanEssen_CC12.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Yeo_JNP11.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Power_Neuron11.study]]></file1>
   </study_metadata_file>
   <study_metadata_file>
      <file1><![CDATA[Glasser_JN11.study]]></file1>
   </study_metadata_file>
</Spec_File>
